---
title: Fyrestead <br/>Agile Technologies
timezone: America\New York
collections:
  posts:
    title: Posts
    output: false
  uploads:
    title: Uploads
    output: false
theme: jekyll-theme-tactile
description: technology solutions that conforms to <em>you</em>
